name: build

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Fetch BtbN/FFmpeg-Builds
      run: |
        sudo apt install -y unzip
        wget https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip
        unzip ffmpeg-master-latest-win64-gpl.zip

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ffmpeg-master-latest-win64-gpl/ffmpeg-master-latest-win64-gpl/bin/ffmpeg.exe
        tag_name: nightly
        make_latest: true
